### ISSUE TITLE
vroom issue

### ISSUE THREAD

**Issue by dcassol** [systemPipeR/systemPipeShiny#52]
## Error
```
terminate called after throwing an instance of 'cpp11::type_error'
  what():  Invalid input type, expected 'integer' actual 'double'
Aborted
```

https://github.com/r-lib/vroom/issues/257

## Solution for 
Install vroom from Github 

**vroom (>= 1.3.0.9000)**
```
devtools::install_dev("vroom")
```

**Comment by lz100** [comment]
The official release comes out on 1.3.1. Just update to the latest vroom will fix the problem. 
vroom (>= 1.3.1)
